apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm-pv-claim
  namespace: romm
  labels:
    app: romm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---